image: docker:git

stages:
  - deploy

before_script:
  - apk --update add nodejs nodejs-npm

services:
  - docker:stable-dind

publish:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --access public .
